# Generated by Django 3.1.6 on 2021-05-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100, verbose_name='Produttore')),
                ('model', models.CharField(max_length=100, verbose_name='Modello')),
                ('year', models.CharField(max_length=4, verbose_name='Anno')),
                ('engine', models.CharField(choices=[('petrol', 'Benzina'), ('diesel', 'Diesel')], default='petrol', max_length=10, verbose_name='Motore')),
                ('cylinders', models.CharField(choices=[('900', '900'), ('1000', '1000'), ('1200', '1200'), ('1300', '1300'), ('1500', '1500'), ('1600', '1600'), ('2000', '2000')], max_length=16, verbose_name='Cilindrata')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='CarFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.car')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, verbose_name='Codice')),
                ('typology', models.CharField(choices=[('air', 'Aria'), ('oil', 'Olio'), ('passenger', 'Abitacolo'), ('diesel', 'Gasolio'), ('gas', 'Gas')], max_length=32, verbose_name='Tipologia')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name="Quantita'")),
                ('cars', models.ManyToManyField(through='warehouse.CarFilter', to='warehouse.Car', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Filtro',
                'verbose_name_plural': 'Filtri',
            },
        ),
        migrations.AddField(
            model_name='carfilter',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.filter'),
        ),
        migrations.AddField(
            model_name='car',
            name='filters',
            field=models.ManyToManyField(through='warehouse.CarFilter', to='warehouse.Filter', verbose_name='Filtri'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make', 'model', 'engine')},
        ),
    ]
