# Generated by Django 3.1.6 on 2021-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Auto'},
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Produttore'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modello'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Anno'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make', 'model')},
        ),
    ]
