# Generated by Django 3.2 on 2021-05-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primario'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(choices=[('900', '900'), ('1000', '1000'), ('1200', '1200'), ('1300', '1300'), ('1500', '1500'), ('1600', '1600'), ('1700', '1700'), ('1900', '1900'), ('2000', '2000')], max_length=16, verbose_name='Cilindrata'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.car', verbose_name='Auto'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.filter', verbose_name='Filtro'),
        ),
    ]
