# Generated by Django 3.1.6 on 2021-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210227_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('petrol', 'Benzina'), ('diesel', 'Diesel')], default='petrol', max_length=10, verbose_name='Motore'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make', 'model', 'engine')},
        ),
    ]
