# Generated by Django 3.2 on 2021-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210514_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='primary',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, verbose_name='Primario'),
        ),
    ]
