# Generated by Django 3.2 on 2021-05-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_filter_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='primary',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=4, verbose_name='Primario'),
        ),
    ]
