# Generated by Django 3.1.6 on 2021-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210227_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Codice')),
                ('typology', models.CharField(max_length=100, verbose_name='Tipologia')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
