# Generated by Django 3.1.6 on 2021-03-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Filtro', 'verbose_name_plural': 'Filtri'},
        ),
        migrations.AddField(
            model_name='filter',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.car'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name="Quantita'"),
        ),
    ]
