# Generated by Django 3.1.6 on 2021-03-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20210320_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.car', verbose_name='Auto'),
        ),
    ]
