# Generated by Django 3.2.3 on 2021-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_car_oil_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='oil_quantity',
            field=models.FloatField(default=0, verbose_name="Quantita' Olio"),
        ),
    ]
