# Generated by Django 3.2.3 on 2021-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_car_oil_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='oil_specific',
            field=models.CharField(choices=[('RN0710', 'RN0710'), ('RN0720', 'RN0720'), ('RN17', 'RN17')], default='RN0710', max_length=16, verbose_name='Specifica Olio'),
        ),
    ]
