# Generated by Django 3.1.6 on 2021-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20210320_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='filters',
            field=models.ManyToManyField(to='warehouse.Filter'),
        ),
    ]
