# Generated by Django 3.1.6 on 2021-03-27 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20210327_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.PositiveIntegerField(default=0, verbose_name='Cilindrata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='filters',
            field=models.ManyToManyField(to='warehouse.Filter', verbose_name='Filtri'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='typology',
            field=models.CharField(choices=[('air', 'Aria'), ('oil', 'Olio'), ('passenger', 'Abitacolo'), ('diesel', 'Gasolio'), ('gas', 'Gas')], max_length=32, verbose_name='Tipologia'),
        ),
    ]
