# Generated by Django 3.1.6 on 2021-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20210327_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.PositiveIntegerField(default=0, verbose_name='Cilindrata'),
        ),
    ]
