# Generated by Django 3.1.6 on 2021-03-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20210327_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.PositiveIntegerField(choices=[(900, '900 (Benzina)'), (1000, '1000 (Benzina)'), (1200, '1200 (Benzina)'), (1300, '1300 (Benzina)'), (1500, '1500 (Diesel)'), (1600, '1600 (Diesel)'), (2000, '2000 (Diesel)')], default=0, verbose_name='Cilindrata'),
        ),
    ]
