# Generated by Django 3.1.6 on 2021-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20210327_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.PositiveIntegerField(choices=[(900, 900), (1000, 1000)], default=900, verbose_name='Cilindrata'),
        ),
    ]
