# Generated by Django 3.1.6 on 2021-05-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20210327_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(choices=[('900', '900'), ('1000', '1000'), ('1200', '1200'), ('1300', '1300'), ('1500', '1500'), ('1600', '1600'), ('2000', '2000')], max_length=16, verbose_name='Cilindrata'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
